### ISSUE TITLE
import error Ubuntu 16.04

### ISSUE THREAD

**Issue by caenyon** [boppreh/keyboard#6] opened 2016-08-06 12:43 UTC
Importing the package doesn't work on my machine (Ubuntu 16.04):
```
Traceback (most recent call last):
  File "/home/canyon/git/keyboard_fork/test.py", line 1, in <module>
    import keyboard
  File "/home/canyon/git/keyboard_fork/keyboard/__init__.py", line 1, in <module>
    from .keyboard import *
  File "/home/canyon/git/keyboard_fork/keyboard/keyboard.py", line 8, in <module>
    from. import nixkeyboard as os_keyboard
  File "/home/canyon/git/keyboard_fork/keyboard/nixkeyboard.py", line 49, in <module>
    assert is_keypad_regular == is_keypad_shifted
AssertionError
```

The assertion fails at keycode 55. This is the relevant output of `dumpkeys --keys-only`:
```
...
keycode  55 = KP_Multiply     
	altgr	keycode  55 = Hex_C           
	shift	alt	keycode  55 = Hex_C           
	altgr	shiftl	keycode  55 = Hex_C           
	shift	alt	shiftl	keycode  55 = Hex_C           
	altgr	shiftr	keycode  55 = Hex_C           
	shift	alt	shiftr	keycode  55 = Hex_C           
	altgr	shiftl	shiftr	keycode  55 = Hex_C           
	shift	alt	shiftl	shiftr	keycode  55 = Hex_C           
	altgr	ctrll	keycode  55 = Hex_C           
	shift	alt	ctrll	keycode  55 = Hex_C           
	altgr	shiftl	ctrll	keycode  55 = Hex_C           
	shift	alt	shiftl	ctrll	keycode  55 = Hex_C           
	altgr	shiftr	ctrll	keycode  55 = Hex_C           
	shift	alt	shiftr	ctrll	keycode  55 = Hex_C           
	altgr	shiftl	shiftr	ctrll	keycode  55 = Hex_C           
	shift	alt	shiftl	shiftr	ctrll	keycode  55 = Hex_C  
...
```

I'm not sure if this could be causing the issue, but I'm using the German keyboard layout.

**EDIT:** the import works fine if comment the assertion line.

**Comment by caenyon** [comment] 2016-08-06 12:44
import works with commented assert line

**Comment by crazyquark** [comment] 2016-10-15 18:16
I have the same problem on Raspbian.

**Comment by boppreh** [comment] 2016-10-15 18:18
I have a Raspbian here, checking it right now.

**Comment by boppreh** [comment] 2016-10-15 18:27
`dumpkeys` was reporting that some keys had empty names when shift was pressed. The module now assumes the name is unchanged in those cases. 

The fix has been committed to master, but it'll take a while to publish a version.

**Comment by boppreh** [comment] 2016-10-15 18:31
Tested on German keyboard layout and the problem is gone. 

I'm closing the issue.

**Closed by boppreh** 2016-10-15 18:31 UTC
