### ISSUE TITLE
Getting an exception on python 3.7

### ISSUE THREAD

**Issue by YourPollution** [boppreh/keyboard#199] opened 2018-08-16 08:02 UTC
Hey.
I using your library for my macro. Src - https://github.com/YourPollution/PyMacros-Fortnite
Btw, 2 users got this exception:
![image](https://user-images.githubusercontent.com/36301723/44196153-d00a0b00-a143-11e8-9903-94433e424afd.png)

*I use x64 windows and it works good.*

**Comment by boppreh** [comment] 2018-08-16 11:00
Hi

Thank you for the bug report, but this is a duplicate of https://github.com/boppreh/keyboard/issues/186. A fix is already available on the master branch, and will be pushed out on the next release.

Sorry for the inconvenience.

**Closed by boppreh** 2018-08-16 11:00 UTC
