### ISSUE TITLE
macOS "Quartz" Import Error 

### ISSUE THREAD

**Issue by seanpianka** [boppreh/keyboard#142] opened 2018-03-24 21:33 UTC
```
~ » uname -a                                                                               
Darwin helium 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin
```

I received the following error after installing the latest version of `keyboard` and attempting to import it:

```
Python 3.6.4 (default, Mar  9 2018, 23:15:12)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/keyboard/__init__.py", line 103, in <module>
    from. import _darwinkeyboard as _os_keyboard
  File "/usr/local/lib/python3.6/site-packages/keyboard/_darwinkeyboard.py", line 3, in <module>
    import Quartz
ModuleNotFoundError: No module named 'Quartz'
```

This issue was resolved by:

`$ pip install pyobjc-framework-Quartz`

...a solution found here: https://github.com/SavinaRoja/PyUserInput/issues/13#issuecomment-104205226

**Comment by glitchassassin** [comment] 2018-03-24 22:07
Duplicate of #107; if I'm not mistaken, this is fixed in the latest master branch, but has not yet been pushed to PyPI.

**Comment by boppreh** [comment] 2018-03-26 23:24
PyPI now has v0.13.0 with the fix mentioned, so this should be a duplicate. Feel free to reopen the issue if the problem persists.

**Closed by boppreh** 2018-03-26 23:24 UTC
Labels: bug, osx
