### ISSUE TITLE
Duplicate keypad codes

### ISSUE THREAD

**Issue by glitchassassin** [boppreh/keyboard#41] opened 2017-01-19 14:30 UTC
`keyboard` currently maps certain numpad keys to the same key code as other function keys. Examples are `num *` and `print screen`, `num 6` and `right`, `num 9` and `page up`, etc.

When I call `press_and_release('print screen')`, instead of copying the screen to the clipboard, I get a `*` character. When I call `press_and_release('num 8')`, I get an up-arrow keypress instead. (Note that if I use `keypad 8` it prints an 8 as expected.)

Could you clarify how this behavior should work? (Below I've included the output of the `_os_keyboard.to_scan_code` dict for your reference.)

    {u"'": (40, False),
    u'+': (78, False),
    u',': (51, False),
    u'-': (12, False),
    u'.': (52, False),
    u'/': (53, False),
    u'0': (11, False),
    u'1': (2, False),
    u'2': (3, False),
    u'3': (4, False),
    u'4': (5, False),
    u'5': (6, False),
    u'6': (7, False),
    u'7': (8, False),
    u'8': (9, False),
    u'9': (10, False),
    u';': (39, False),
    u'<00>': (84, False),
    u'=': (13, False),
    u'[': (26, False),
    u'\\': (43, False),
    u']': (27, False),
    u'`': (41, False),
    u'a': (30, False),
    u'alt': (56, False),
    'alt gr': 541,
    u'b': (48, False),
    u'backspace': (14, False),
    u'break': (70, False),
    u'c': (46, False),
    u'caps lock': (58, False),
    u'ctrl': (29, False),
    u'd': (32, False),
    u'delete': (83, False),
    u'down': (80, False),
    u'e': (18, False),
    u'end': (79, False),
    u'enter': (28, False),
    u'esc': (1, False),
    u'f': (33, False),
    u'f1': (59, False),
    u'f10': (68, False),
    u'f11': (87, False),
    u'f12': (88, False),
    u'f13': (124, False),
    u'f14': (125, False),
    u'f15': (126, False),
    u'f16': (127, False),
    u'f2': (60, False),
    u'f3': (61, False),
    u'f4': (62, False),
    u'f5': (63, False),
    u'f6': (64, False),
    u'f7': (65, False),
    u'f8': (66, False),
    u'f9': (67, False),
    u'g': (34, False),
    u'h': (35, False),
    u'help': (86, False),
    u'home': (71, False),
    u'i': (23, False),
    u'insert': (82, False),
    u'j': (36, False),
    u'k': (37, False),
    u'l': (38, False),
    u'left': (75, False),
    u'left windows': (91, False),
    u'm': (50, False),
    'menu': (93, False),
    u'n': (49, False),
    u'num *': (55, False),
    u'num +': (78, False),
    u'num -': (74, False),
    u'num /': (53, False),
    u'num 0': (82, False),
    u'num 1': (79, False),
    u'num 2': (80, False),
    u'num 3': (81, False),
    u'num 4': (75, False),
    u'num 5': (76, False),
    u'num 6': (77, False),
    u'num 7': (71, False),
    u'num 8': (72, False),
    u'num 9': (73, False),
    u'num del': (83, False),
    u'num enter': (28, False),
    u'num lock': (69, False),
    u'o': (24, False),
    u'p': (25, False),
    u'page down': (81, False),
    u'page up': (73, False),
    u'pause': (69, False),
    'print screen': (55, False),
    u'q': (16, False),
    u'r': (19, False),
    u'right': (77, False),
    u'right alt': (56, False),
    u'right ctrl': (29, False),
    u'right shift': (54, False),
    u'right windows': (92, False),
    u's': (31, False),
    u'scroll lock': (70, False),
    u'shift': (42, False),
    u'space': (57, False),
    u'sys req': (84, False),
    u't': (20, False),
    u'tab': (15, False),
    u'u': (22, False),
    u'up': (72, False),
    u'v': (47, False),
    u'w': (17, False),
    u'x': (45, False),
    u'y': (21, False),
    u'z': (44, False)}

**Comment by boppreh** [comment] 2017-01-19 20:43
Ok, so the problem is that Windows is telling us that two virtual key codes are mapped to the same scan code. This also happens with `d` and `volume mute`, for example, but the bug is not triggered out of luck (the correct one appears first in the list).

When you say you want `print screen`,  there's a function that maps it to a scan code. But that Windows wants to send events is a virtual key code, so we have to convert. But because of the previous ambiguity, this scan code may end up triggering the wrong key.

A solution is to map it first to a virtual key code, *then* to a scan code. Even if the scan code is wrong, what matters for sending events is the virtual key code, so it should be ok (with exception of some enterprise software that forwards events, but that's another matter).

So that's what I did. Now when the Windows backend is mapping a name, it first tries to map to a virtual key code, and only goes for scan codes if none is found. The downside is that this is less portable between Windows and Linux, and the whole thing is a bit hacky.

But it should be working now.

**Comment by xoviat** [comment] 2017-02-05 23:27
I have run into this problem when calling `add_hotkey` on numbers 4-9 on the numberpad. The solution is probably to modify the names of keys to numbers if `is_keypad` is true (or whatever the attribute is).

**Comment by glitchassassin** [comment] 2017-02-24 16:50
I'm running into a new but perhaps related issue with the latest version of `keyboard`.

    keyboard.press_and_release("_") # Types "-"
    keyboard.press_and_release("?") # Types "/"

Other shift-activated special characters work fine. I think that after setting the `shift` state, the numpad `/` and `-` keys are being triggered (and shift has no effect on them) rather than the regular keyboard keys.

**Comment by boppreh** [comment] 2017-02-24 16:53
Press and release is from the "hotkey" family, and thus case-less. Try "write", that may be the behavior you are looking for. 

If it works for you, it would be a good idea to update the docs to make this distinction explicit.

**Comment by glitchassassin** [comment] 2017-02-24 18:24
Apologies. Here's the full code of my test. You can paste this directly into the interactive interpreter:

    import keyboard
    def test():
        keyboard.press("shift")
        keyboard.press_and_release("-")
        keyboard.press_and_release("a")
        keyboard.release("shift")

    test() # Types "-A" (instead of "_A"

Note that the `a` is typed with shift properly, but the `-` is unaffected. This is normal behavior for the numpad `-`, but the key I was trying to trigger was the regular keyboard `-`.

I think the solution may be to flag at least the following numpad math buttons as numpad keys:

* [_winkeyboard.py:220](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L220)
* [_winkeyboard.py:221](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L221)
* [_winkeyboard.py:223](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L223)
* [_winkeyboard.py:225](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L225)

Potentially these also, if that doesn't solve the issue, though they might be correct:
* [_winkeyboard.py:276](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L276)
* [_winkeyboard.py:277](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L277)
* [_winkeyboard.py:278](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L278)
* [_winkeyboard.py:279](https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L279)

Thoughts?

**Comment by glitchassassin** [comment] 2017-02-24 18:41
Submitted a pull request for your review.

**Comment by boppreh** [comment] 2017-08-28 00:58
Hi glitch

Is this still giving you trouble, or can I close the issue? The last example is working properly on my machine too.

**Closed** 2017-12-27 17:05 UTC
Labels: bug, waiting-for-feedback, windows

**Comment by IceflowRE** [comment] 2019-07-04 21:30
Still have some problems: e.g.
79: Keypad 1 & end
80: Keypad 2 & down (arrow down key)
81: Keypad 3 & page down

Win10 with german QWERTZ keyboard.
