### ISSUE TITLE
Failed to show QDialog with set hotkey

### ISSUE THREAD

**Issue by skys215** [boppreh/keyboard#75] opened 2017-07-12 14:51 UTC
Hi,
    I'm developing a software like todo-list with PyQt5. What I want to do is: when I press the hotkey which I set, show the window of to-do list.
    It's working in a way, the dialog shows up. But the content of the dialog is not showing and the program starts to crash with this error:
```
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
```
 If I open same dialog from the system tray, it doesn't crash.

The weird thing is, if I create another dialog and keep open(not closing the window), the program won't crash but printing some warning message(`QObject::startTimer: Timers cannot be started from another thread`) in the console after I press the hotkey which I set. It works perfect.  I thought it may be the dialog wasn't "initialized"(never showed up on the screen) so it fail to show the dialog? I tried to show the dialog right after the program starts, then close the window with mouse, and press the hotkey again, the problem remains, but without that warning(`QBasicTimer.......QThread`). 

I'm new to PyQt, so I have no idea how to debug it. I'm guessing that maybe some kind of context is missing right there when running the callback function. Or could be something else. I'm wondering if there's something to do with the keyboard module which you wrote.
Here is the key part of my program:

```python
if __name__ == '__main__':
    mainDialog = QDialog()
    ui = Ui_Dialog() #It's created by QtCreator
    ui.setupUi(mainDialog)

   # there's a system tray which keep program running even the window has closed
    QApplication.setQuitOnLastWindowClosed(False)
    keyboard.add_hotkey('ctrl+alt+d', mainDialog.show)
    sys.exit(app.exec_())
```

   I'm running the program on `Windows 10`, running with Python version `3.6.1`, `PyQt5`, `Qt5.9.1`.

Thanks.

**Comment by boppreh** [comment] 2017-07-12 16:35
Hi

The answer is in the error itself: `[...] can only be used with threads started with QThread`. Hotkeys in `keyboard` are processed asynchronously, which means that your `mainDialog.show` callback is invoked from a separate thread. Qt is a bit brittle in this aspect and doesn't allow a UI call from a non-UI thread (i.e. should inherit `QThread` instead of Python's `threading.Thread`).

This is not a `keyboard` issue, but would have happened with any code that calls `mainDialog.show` from inside a `threading.Thread`.

The solution is to use Qt's **signals and slots**. This way you can emit a signal from the keyboard handler, and the slot will call the desired method from inside the main thread.

I'm closing the issue, but if you still fail to get your code to work and believe `keyboard` is to blame, or have any suggestions that could be implemented on this side, feel free to reopen the issue.

**Closed by boppreh** 2017-07-12 16:35 UTC

**Comment by skys215** [comment] 2017-07-13 12:33
Thank you for the answer.

**Comment by hansonap** [comment] 2022-02-17 16:42
I ran into this very issue and came to the same conclusion a few hours later. A note in README.md about qt would be great.  #347 appears to be duplicate of this issue as well.
