### ISSUE TITLE
add_hotkey must do release shift\ctrl\alt keys and press them again with other normal keys

### ISSUE THREAD

**Issue by 26awen** [boppreh/keyboard#109] opened 2017-11-26 10:45 UTC
For example set a hotkey like below:
 keyboard.add_hotkey('shift+a', lambda : keyboard.write('xxxxx'))
 keyboard.wait()

this will work the first time. but if I hold the shift key and press 'a' again ,it wont work.
I must release the shift key and press shift+a both to make it work.

**Comment by boppreh** [comment] 2017-11-28 00:57
Thanks for the feedback. I think this is a duplicate of https://github.com/boppreh/keyboard/issues/91, and it's being worked on.

**Closed by boppreh** 2017-11-28 00:57 UTC
